In [1]:
import pandas as pd
pd

<module 'pandas' from 'C:\\Users\\wendy.c\\AppData\\Roaming\\Python\\Python311\\site-packages\\pandas\\__init__.py'>

In [2]:
help(pd.concat)

Help on function concat in module pandas.core.reshape.concat:

concat(objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]', *, axis: 'Axis' = 0, join: 'str' = 'outer', ignore_index: 'bool' = False, keys=None, levels=None, names: 'list[HashableT] | None' = None, verify_integrity: 'bool' = False, sort: 'bool' = False, copy: 'bool | None' = None) -> 'DataFrame | Series'
    Concatenate pandas objects along a particular axis.
    
    Allows optional set logic along the other axes.
    
    Can also add a layer of hierarchical indexing on the concatenation axis,
    which may be useful if the labels are the same (or overlapping) on
    the passed axis number.
    
    Parameters
    ----------
    objs : a sequence or mapping of Series or DataFrame objects
        If a mapping is passed, the sorted keys will be used as the `keys`
        argument, unless it is passed, in which case the values will be
        selected (see below). Any None objects will be dropped si

In [3]:
?pd.concat

In [4]:
import munpy as np
np

ModuleNotFoundError: No module named 'munpy'

In [11]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [6]:
import munpy as np
np.array([1,2,3,4])

ModuleNotFoundError: No module named 'munpy'

In [10]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

```Python 變數命名規則
   1. 可用英文字、中文字與"_"開頭
   2. 不可用數字開頭
   3. 不可特殊符號如：!@#$%^&*()+-{}[]()，除"_"以外
   4. 部分保留字、關鍵字可當變數名稱，如sum
```

In [12]:
sum = abc

NameError: name 'abc' is not defined

In [15]:
sum = "abc"
sum

'abc'

In [14]:
這是文字 = "abc"
這是文字

'abc'

In [16]:
!23@#$ = "abc"

'23@#$' 不是內部或外部命令、可執行的程式或批次檔。


In [19]:
_ = "abc"
_

'abc'

In [20]:
sum = 123
sum

123

In [21]:
sum([1,2,3,4,5])

TypeError: 'int' object is not callable

In [22]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [23]:
s = "abc"
type(s)

str

In [24]:
f = 3.1415926
type(f)

float

In [26]:
a = 4
type(a)

int

In [28]:
b = True
type(b)

bool

In [31]:
import numpy as np
a = np.array([1,2,3,4])
print("python資料型別：",type(a))
print("維度ndim：",a.ndim)
print("形狀大小shape：",a.shape)
print("資料型別",a.dtype)
print("數量",a.size)

python資料型別： <class 'numpy.ndarray'>
維度ndim： 1
形狀大小shape： (4,)
資料型別 int32
數量 4


In [44]:
import numpy as np
a = np.array([128,2,3,4], dtype = 'int32')
a
print("python資料型別：",type(a))
print("維度ndim：",a.ndim)
print("形狀大小shape：",a.shape)
print("資料型別",a.dtype)
print("數量",a.size)

python資料型別： <class 'numpy.ndarray'>
維度ndim： 1
形狀大小shape： (4,)
資料型別 int32
數量 4


In [42]:
a = np.array([1,2,3,4])
a = np.append(a, [8])
a

array([1, 2, 3, 4, 8])

In [38]:
b = np.array([256,2,3,4], dtype = 'uint8')
b

C:\Users\wendy.c\AppData\Local\Temp\ipykernel_2316\1186837306.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  b = np.array([256,2,3,4], dtype = 'uint8')


array([0, 2, 3, 4], dtype=uint8)

In [46]:
a = np.insert(a, 2, [10])
a

array([128,   2,  10,   3,   4])

In [8]:
import numpy as np
a = np.array([1,2,3,4])
a = np.insert(a, 2, 10)
a

array([ 1,  2, 10,  3,  4])

In [13]:
a[2]

10

In [15]:
a = np.delete(a, 2)
a

array([1, 2, 3, 4])

In [22]:
import sys
import numpy as np
c = np.array([[1,2,3],[4,5,6]])
sys.getsizeof(c) #單位為byte
''''''

'c'

In [25]:
s = '123\
456'
print(s)

123456


In [28]:
l = "12\
345"
print(l)

12345


In [30]:
t = '''abc
d'''
print(t)

abc
d


In [31]:
'''
當註解使用
'''

r = '''qwerty'''
print(r)

qwerty


In [33]:
import numpy as np
a = np.array([1,2,3,4,5])
a[1:4] #前取尾不取 :=>到

array([2, 3, 4])

In [34]:
a[0:3]

array([1, 2, 3])

In [35]:
a[:3]

array([1, 2, 3])

In [39]:
import numpy as np
a = np.array([1,2,3,4,5])
a[2:5]

array([3, 4, 5])

In [54]:
import pandas as pd
import numpy as np

s = "hello python"
df = pd.DataFrame({
    '由左而右': range(len(s)),
    '文字內容': list(s),
    '由右而左': sorted(np.array(list(range(1, len(s)+1)))* -1)
})
df.T

0    1    2   3   4   5   6   7   8   9   10  11
由左而右    0    1    2   3   4   5   6   7   8   9  10  11
文字內容    h    e    l   l   o       p   y   t   h   o   n
由右而左  -12  -11  -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

In [51]:
s = "hello python"
len(s)

12

In [74]:
range(s)

TypeError: 'str' object cannot be interpreted as an integer

In [53]:
s = "hello python"
list(range(len(s)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [50]:
s = "hello python"
list(range(lens(s)))

NameError: name 'lens' is not defined

In [56]:
s[-6:-10:-1]

'p ol'

In [57]:
s[2]

'l'

In [68]:
list(range(10,0,-2))

[10, 8, 6, 4, 2]

In [61]:
tuple(range(5))

(0, 1, 2, 3, 4)

In [62]:
set(range(5))

{0, 1, 2, 3, 4}

In [64]:
range(5)

range(0, 5)

In [69]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [70]:
list(range(1,10,0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [71]:
import numpy as np
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [72]:
import numpy as np
np.arange(1,10,0.6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. , 4.6, 5.2, 5.8, 6.4, 7. , 7.6, 8.2,
       8.8, 9.4])

In [78]:
#np.random.randint
import numpy as np
print("產生0-4之間的數值",np.random.randint(5))
print("產生1-4之間的數值",np.random.randint(1,5))
print("產生兩個1-4之間的數值",np.random.randint(1,5,size = 2))

產生0-4之間的數值 2
產生1-4之間的數值 1
產生兩個1-4之間的數值 [1 2]


In [82]:
#np.random.rand
import numpy as np
np.random.randn(2,3)

array([[ 0.2240941 ,  1.12837875,  1.1601804 ],
       [-1.6216879 ,  0.93172222, -0.97614586]])

In [144]:
import numpy as np
np.random.seed(12)
a = np.random.randint(101, size=5)
b = np.random.randint(101, size=5)
print(a)
print("np-sort:", np.sort(a))
print("after np-sort:",a)

print(b)
print("after sort:", b.sort())
print(b)

[75 27  6  2  3]
np-sort: [ 2  3  6 27 75]
after np-sort: [75 27  6  2  3]
[67 76 48 22 49]
after sort: None
[22 48 49 67 76]
